user_name: 233
pass_word: 233

chromedrive_path: /usr/local/bin/chromedriver

links_id:
        芜湖大司马:
                - https://www.douyu.com/606118
        贝拉小姐姐:
                - https://www.douyu.com/3276456
        小小奶瓶儿:
                - https://www.huya.com/356127
        张爱玲Aily:
                - https://www.huya.com/974349
        张爱玲Aily【小号】:
                - https://www.huya.com/21743710
